version: 2
updates:
- package-ecosystem: nuget
  directories:
    - "src/<repo-name>"
    - "src/Tests/<repo-name>.Tests"
  schedule:
    interval: daily
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
