version: 2
updates:
- package-ecosystem: nuget
  directories:
    - "src/Markdowned"
    - "src/Markdowned.Abstractions"
    - "src/Markdowned.Cli"
    - "src/Tests/Markdowned.Tests"
    - "src/Tests/Markdowned.Cli.Tests"
    - "src/Tests/Markdowned.Integration.Tests"
  schedule:
    interval: daily
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
- package-ecosystem: "devcontainers"
  directory: "/"
  schedule:
    interval: weekly
- package-ecosystem: npm
  directory: "/assets"
  schedule:
    interval: weekly
